Revert "build(deps): bump sigstore/cosign-installer from 2.8.1 to 3.0.1"
This reverts commit eceacc854304748cc19f115277b0342381788626.

Reverting this dependabot change because it breaks the build.

Run cosign sign quay.io/cilium/tetragon-operator-ci@sha256:32851e6980638f3cd364fd52174b041de3e4bf433b3b49c57f58c0f2dc341970
Generating ephemeral keys...
Retrieving signed certificate...
Successfully verified SCT...

	Note that there may be personally identifiable information associated with this signed artifact.
	This may include the email address associated with the account with which you authenticate.
	This information will be used for signing this artifact and will be stored in public transparency logs and cannot be removed later.

By typing 'y', you attest that you grant (or have permission to grant) and agree to have this information stored permanently in transparency logs.
Are you sure you would like to continue? [y/N] Error: signing [quay.io/cilium/tetragon-operator-ci@sha256:32851e6980638f3cd364fd52174b041de3e4bf433b3b49c57f58c0f2dc341970]: signing digest: should upload to tlog: user declined the prompt
main.go:74: error during command execution: signing [quay.io/cilium/tetragon-operator-ci@sha256:32851e6980638f3cd364fd52174b041de3e4bf433b3b49c57f58c0f2dc341970]: signing digest: should upload to tlog: user declined the prompt
Error: Process completed with exit code 1.

Signed-off-by: Kornilios Kourtis <kornilios@isovalent.com>