docs: Fix Kubernetes installation guide for zsh
When running the K8s installation guide with zsh the following commands:

  EXTRA_HELM_FLAGS="--set tetragon.hostProcPath=/procHost"
  helm install tetragon ${EXTRA_HELM_FLAGS} cilium/tetragon -n kube-system

fail with:

  Error: unknown flag: --set tetragon.hostProcPath

The reason for this is that zsh does not split into words when it
expands parameters by default [2]. For example, in a zsh shell:

  EXTRA_FLAGS="--namespace kube-system"; strace -e trace=execve kubectl get pods ${EXTRA_FLAGS} 2>&1 | grep -m1 kubectl
  execve("/usr/bin/kubectl", ["kubectl", "get", "pods", "--namespace kube-system"], 0x7ffe5a984d38 /* 63 vars */) = 0

Fix this by using arrays to pass extra Helm flags which works in both
bash and zsh shells.

[1] https://linux.die.net/man/1/zshexpn

Signed-off-by: Ioannis Androulidakis <androulidakis.ioannis@gmail.com>