testing: avoid error pipes when executing programs
We are seeing tests fail with the following errors:
    kprobe_sigkill_test.go:33: error reading stderr> : read |0: file already closed
    kprobe_sigkill_test.go:33: error reading stdout> : read |0: file already closed

One potential reason for this is that we wait on the commands before the
reads from the stderr/stdout pipes have completed, which is incorrect:
https://pkg.go.dev/os/exec#Cmd.StderrPipe.

this patch fixes this.

Signed-off-by: Kornilios Kourtis <kornilios@isovalent.com>