update clang-format to properly handle enums
It seems that our clang-format is incompatible with checkpatch.

Here's why: the next patch wants to add a new entry to an enum in
bpf/process/types/basic.h.

Specifically, adding the following lines:

>       /* const_buf_type is a type for buffers with static size that is passed
>        * in the meta argument
>        */
>       const_buf_type = 18,
>

By doing so, checkpatch complains with the following error:
 Error: ERROR:CODE_INDENT: code indent should use tabs where possible
  #36: FILE: bpf/process/types/basic.h:33:
  +        * in the meta argument$

I tried to just switch the modified line to use tabs but this made
clang-format unhappy.

Why clang-format uses spaces even if we have specified to alwyas use
tabs?  (UseTab: Always)

Good question! I think it's because clang-format thinks it's OK to add
the first enum value into the first line.

To avoid the above problem, we can fix clang-format and update the files
so that enums are indented with tabs. To do this we need to specify:

AllowShortEnumsOnASingleLine: false

The above was introduced in clang-format-11, so we need to bump the version.

But bumping it to clang-format-11, will not work due to this bug:
https://reviews.llvm.org/D99840. So we need to use clang-format-14 that
fixes this bug.

Above means we need to base our docker image on a later ubuntu version.

NB: The new clang-format results in updates in some assembly code as
well, but this seems minimal, so I think is fine.

Signed-off-by: Kornilios Kourtis <kornilios@isovalent.com>