watcher: add test for "fast" k8s API server
[ upstream commit 7043d06fc5d79be8a9147e6fa98387739a0b41ba ]

This commit ads a test where a lookup for a pod via its container id happens
after the pod was deleted. This case, might happen if a pod is started and
deleted from the cache before user-space gets a chance to associate a pod with
an exec event.

Example:
go test ./pkg/watcher -test.run TestFastK8s -test.v
=== RUN   TestFastK8s
    watcher_test.go:32: time="2024-09-17T13:38:51+02:00" level=info msg="Initialized informer cache" count=0 informer=pod

    watcher_test.go:95: adding pod
    watcher_test.go:103: deleting pod
    watcher_test.go:108:
                Error Trace:    /home/kkourt/src/tetragon/pkg/watcher/watcher_test.go:108
                Error:          Should be true
                Test:           TestFastK8s
                Messages:       deleted pod should be found

Signed-off-by: Kornilios Kourtis <kornilios@isovalent.com>