tracepoint_test: use sensor/test checker
This patch adds the sensor/test TestChecker in the generic tracepoint
tests.

The immediate result is that failing the test can be failed quicker.

For example, if we modify the code so that the ArgFilterLseek test fails:
        op := func() {
                t.Logf("Calling lseek...\n")
-               unix.Seek(fd, 0, whence)
+               // unix.Seek(fd, 0, whence)
                unix.Seek(fd, 0, whence+1)
        }

Then, with this patch the test fails in 4.5s [1], while without in 46s
[2].

Additionally, the idea here is to try and use this approach in the GH
actions environment and see how well it works. If it does, we can use it
to make our testing more reliable and predicatable.

1:
observer_test_json.go:153: time="2022-05-30T14:28:47+02:00" level=info msg="seen events on all CPUs, finalizing test"
...
--- FAIL: TestGenericTracepointArgFilterLseek (4.46s)

2:
tracepoint_test.go:199: error: JsonTestCheck failed after 20 retries: JsonEOF: failed to match after 167 events: err:Got 0 events while expecting at least 1
...
--- FAIL: TestGenericTracepointArgFilterLseek (45.84s)

Signed-off-by: Kornilios Kourtis <kornilios@isovalent.com>