bpf: introduce bpf_errmetrics
This commit introduces a map for error metrics.

It is inspired by a similar facility that exists in cilium. See, for
example, https://github.com/cilium/cilium/pull/30972.

The general idea is to have a map that keeps information about errors
on certain code locations. This can be unexpected errors or errors that,
for whatever reason, are not properly handled.

The errors are kept in a per-cpu lru hash map, with a key that includes
the error number, a file id, and a line location.

fileids.h maintains the mapping between filenames and fileids. Note that
if a id does not exist for a file, there will be a comilation error and
the id would have to be added to the table.

For example, if the current entry in fileids.h is removed, the following
error will appear when trying to compile the bpf programs:
cgroup/bpf_cgtracker.c:64:3: error: call to 'compile_time_error' declared with 'error' attribute: add "cgroup/bpf_cgtracker.c" to the ids list (fileids.h)

As a first use of this, we add a wrapper for map_update_elem and use it
in cgtracker to maintain information for when the mkdir hook was not
able to add the new track id.

The intention is to extend the use of this in other places, which why
the commit adds the header to the exec program so that it can be loaded
as part of the exec sensor.

Subsequent patches will add user-space code for dealing with this.

Signed-off-by: Kornilios Kourtis <kornilios@isovalent.com>