fix(cmd/tetragon-vmtests-run): fixed error case on test panic.
[ upstream commit c32ba0aeb2d9ccade54584b8b85e288918887d1e ]

In case a panic happens during a test, we will never receive a "fail"
`TestEvent` line.
In that case, force-add the test and set it to a failed one.

Example output json:

	{"Time":"2025-10-29T11:47:38.38852348Z","Action":"output","Test":"TestKprobeResolveCurrent","Output":"    logcapture.go:24: time=2025-10-29T11:43:11.967Z level=INFO msg=\"Unloading sensor __base__\"\n"}
	{"Time":"2025-10-29T11:47:38.388551081Z","Action":"output","Test":"TestKprobeResolveCurrent","Output":"    filenames.go:49: keeping export file for TestKprobeResolveCurrent (/tmp/tetragon.gotest.TestKprobeResolveCurrent.33323489.json)\n"}
	{"Time":"2025-10-29T11:47:38.388556651Z","Action":"output","Test":"TestKprobeResolveCurrent","Output":"    logcapture.go:24: time=2025-10-29T11:43:12.022Z level=INFO msg=\"Sensor unloaded\" sensor=__base__ maps-error=[]\n"}
	{"Time":"2025-10-29T11:47:38.388561491Z","Action":"output","Test":"TestKprobeResolveCurrent","Output":"    base.go:198: cleanup: unloading base sensor\n"}
	{"Time":"2025-10-29T11:47:38.388565438Z","Action":"output","Test":"TestKprobeResolveCurrent","Output":"level=info msg=\"Unloading sensor __base__\"\n"}
	{"Time":"2025-10-29T11:47:38.388571599Z","Action":"output","Test":"TestKprobeResolveCurrent","Output":"--- FAIL: TestKprobeResolveCurrent (1.18s)\n"}
	{"Time":"2025-10-29T11:47:38.388579404Z","Action":"output","Test":"TestKprobeResolveCurrent","Output":"panic: runtime error: invalid memory address or nil pointer dereference [recovered, repanicked]\n"}
	{"Time":"2025-10-29T11:47:38.388583822Z","Action":"output","Test":"TestKprobeResolveCurrent","Output":"[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1242ec5]\n"}

As you can see, we only receive `Action: output` lines,
but never receive the `fail` one since a panic is triggered during the test.
Therefore we skip all of them and are not able to mark the test as failed.

Signed-off-by: Federico Di Pierro <nierro92@gmail.com>
Signed-off-by: Tam Mach <tam.mach@cilium.io>