cgtracker_test: skip if test cannot mkdir
In GH runners, we get:

--- FAIL: TestCgTrackerMap (0.12s)
    cgtracker_test.go:73: '/sys/fs/cgroup' is cgroup v1
    cgtracker_test.go:81: failed to create test dir: mkdir /sys/fs/cgroup/cgtracker-test-1715271346: read-only file system

So it seems that we cannot execute the test there. Skip it for now.

Signed-off-by: Kornilios Kourtis <kornilios@isovalent.com>