pkg/grpc: properly initialize tests
The following tests:
 - TestProcessManager_GetProcessExec
 - TestProcessManager_getPodInfoMaybeExecProbe
 - TestProcessManager_GetProcessID

work only if the state is initialized by another test before them. Fix
this, so that we can run the tests on their own.

As an example of a failed test before this patch:
$ ./go-tests/pkg.grpc  -test.run TestProcessManager_getPodInfoMaybeExecProbe
--- FAIL: TestProcessManager_getPodInfoMaybeExecProbe (0.00s)
    process_manager_test.go:128:
                Error Trace:    process_manager_test.go:128
                Error:          Received unexpected error:
                                ciliumState must be initialized before process cache
                Test:           TestProcessManager_getPodInfoMaybeExecProbe
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x153241b]

goroutine 66 [running]:
testing.tRunner.func1.2({0x16fdd60, 0x275a5f0})
        /opt/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
        /opt/go/src/testing/testing.go:1392 +0x39f
panic({0x16fdd60, 0x275a5f0})
        /opt/go/src/runtime/panic.go:838 +0x207
github.com/cilium/tetragon/pkg/process.(*Cache).Purge(...)
        /home/kkourt/src/tetragon/pkg/process/cache.go:130
github.com/cilium/tetragon/pkg/process.FreeCache()
        /home/kkourt/src/tetragon/pkg/process/process.go:82 +0x1b
panic({0x16fdd60, 0x275a5f0})
        /opt/go/src/runtime/panic.go:838 +0x207
github.com/cilium/tetragon/pkg/process.GetPodInfo(...)
        /home/kkourt/src/tetragon/pkg/process/process.go:209
github.com/cilium/tetragon/pkg/grpc.TestProcessManager_getPodInfoMaybeExecProbe(0xc00042eb60?)
        /home/kkourt/src/tetragon/pkg/grpc/process_manager_test.go:130 +0x388
testing.tRunner(0xc00042eb60, 0x1a17f28)
        /opt/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
        /opt/go/src/testing/testing.go:1486 +0x35f

Signed-off-by: Kornilios Kourtis <kornilios@isovalent.com>