[backport/v1.2] tetra/debug: Clone GetDebugResponse entries
[upstream commit b76687bacac928fcff2e60546456a61827983463]

When running command "tetra debug dump processcache", we get sometimes
the following error:

Error: failed to get process dump debug info: rpc error: code = Internal
desc = grpc: error while marshaling: marshaling tetragon.GetDebugResponse:
size mismatch (see https://github.com/golang/protobuf/issues/1609): calculated=1240,
measured=1269

By checking the link provided in the error message, we can see that the
most possible cause of the error is accidental sharing and concurrent mutation
of a Protobuf message or submessage.

To avoid that issue, this patch clones mutable submessages.

We managed to reproduce that in a server with heavy load. This patch
seems to solve that issue.

Signed-off-by: Anastasios Papagiannis <anastasios.papagiannis@isovalent.com>