tetragoninfo: add darwin stub for bpfProbes
[ upstream commit 97373807f4ef6d24fbbb2ff46229eefedf6fa948 ]

Add info_darwin.go with a nil-returning bpfProbes() stub,
matching the existing info_windows.go. Without this, the
tetra CLI fails to build on macOS:

  pkg/tetragoninfo/info.go:84:12: undefined: bpfProbes

Closes #4931
Closes #4932
Ref: https://github.com/Homebrew/homebrew-core/pull/280098

Signed-off-by: Rui Chen <rui@chenrui.dev>